### PR TITLE
Implement message generation and CRC addition.

### PR DESCRIPTION
**Pull request by art103**
Hi, 
I'm not expecting you to merge this change (I had to remove the scanner, as it failed on my setup). 
However, the checksum generation for arbitrary messages might be useful to you, as may the battery percentage code. 
Kind regards,
Richard.

Commit message:
This allows an arbitrary position to be set.
I have also brought the battery, light and position messages over from binsentsu/am43-ctrl.

### CODE REVIEW

**Comment by TheBazeman** [comment]
Hi Richard,

Thanks for the message! Actually I just had started on programming for batt, light and position check yesterday! I will take a look on the checksum generation.

When the scanner fails, it needs elevated rights. But, I have disabled it also in my code now. Have to check the reliability as my code already runs for months without a glitch. Just to be curious why it fails: did you use the provided service file to start the python3 script?

Met vriendelijke groet,

Bas Bahlmann

Van: Richard Taylor [mailto:notifications@github.com]
Verzonden: woensdag 12 februari 2020 22:25
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [TheBazeman/A-OK-AM43-Blinds-Drive] Implement message generation and CRC addition. (#2)


Hi,
I'm not expecting you to merge this change (I had to remove the scanner, as it failed on my setup).
However, the checksum generation for arbitrary messages might be useful to you, as may the battery percentage code.
Kind regards,
Richard.

Commit message:
This allows an arbitrary position to be set.
I have also brought the battery, light and position messages over from binsentsu/am43-ctrl.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/TheBazeman/A-OK-AM43-Blinds-Drive/pull/2

Commit Summary

  *   Implement message generation and CRC addition.

File Changes

  *   M AOK-AM43.py<https://github.com/TheBazeman/A-OK-AM43-Blinds-Drive/pull/2/files#diff-0> (152)

Patch Links:

  *   https://github.com/TheBazeman/A-OK-AM43-Blinds-Drive/pull/2.patch
  *   https://github.com/TheBazeman/A-OK-AM43-Blinds-Drive/pull/2.diff

**Comment by TheBazeman** [comment]
Hi Richard,

I have posted the updated version I created, did manage to simplify it a little bit with your code. Thanks for that!

Met vriendelijke groet,

Bas Bahlmann

Van: Richard Taylor [mailto:notifications@github.com]
Verzonden: woensdag 12 februari 2020 22:25
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [TheBazeman/A-OK-AM43-Blinds-Drive] Implement message generation and CRC addition. (#2)


Hi,
I'm not expecting you to merge this change (I had to remove the scanner, as it failed on my setup).
However, the checksum generation for arbitrary messages might be useful to you, as may the battery percentage code.
Kind regards,
Richard.

Commit message:
This allows an arbitrary position to be set.
I have also brought the battery, light and position messages over from binsentsu/am43-ctrl.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/TheBazeman/A-OK-AM43-Blinds-Drive/pull/2

Commit Summary

  *   Implement message generation and CRC addition.

File Changes

  *   M AOK-AM43.py<https://github.com/TheBazeman/A-OK-AM43-Blinds-Drive/pull/2/files#diff-0> (152)

Patch Links:

  *   https://github.com/TheBazeman/A-OK-AM43-Blinds-Drive/pull/2.patch
  *   https://github.com/TheBazeman/A-OK-AM43-Blinds-Drive/pull/2.diff

**Comment by TheBazeman** [comment]
Hi Richard, I have implemented pieces of your code into mine and added some more. Thanks a lot.

**Comment by art103** [comment]
Great, glad it helped :) 
I've also reverse engineered the upper and lower position setting sequence. Will look at the settings shortly then send another pull request if it's useful.
Regarding scanning, I'm not running this as a service yet (still developing), but as a normal user from the command line.

**Comment by TheBazeman** [comment]
Hi Richard,

Sounds good! Awaiting the pull request ;-)

Scanning: got it disabled now. Seems good so far. Not having the elevated rights is the issue then. When you “su” the python3 command it would have worked.

Met vriendelijke groet,

Bas Bahlmann

Van: Richard Taylor [mailto:notifications@github.com]
Verzonden: vrijdag 14 februari 2020 11:06
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Bas Bahlmann <bas@bahlmann.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [TheBazeman/A-OK-AM43-Blinds-Drive] Implement message generation and CRC addition. (#2)


Great, glad it helped :)
I've also reverse engineered the upper and lower position setting sequence. Will look at the settings shortly then send another pull request if it's useful.
Regarding scanning, I'm not running this as a service yet (still developing), but as a normal user from the command line.

**Pull request closed without merging**
